type Query {
  getDistrito(_id: ID): Distrito
  getDistritos(filter: DistritoFilter, sortby: [SortBy]): [Distrito]
}

type Mutation {
  createDistrito(input: DistritoInput): Boolean
  updateDistrito(_id: ID, input: DistritoInput): Boolean
  deleteDistrito(_id: ID): Boolean
}

type Distrito {
  _id: ID
  departamento: String
  provincia: String
  nombre: String
  codigo: String
  latitud: Float
  longitud: Float
  poligono: [[[Float]]]
}

input DistritoFilter {
  provincia: String
  codigo: String
}

input DistritoInput {
  departamento: String
  provincia: String
  nombre: String
  codigo: String
  latitud: Float
  longitud: Float
  poligono: [[[Float]]]
}
